id = "lina-theme"
name = "Lina"
version = "0.0.1"
schema_version = 1
authors = ["Danilo Campos <hello@danilocampos.cc>"]
description = "Lina theme for Zed"
repository = "https://github.com/danilomcampos/lina-zed"
